ci_service: travis_ci
coverage_service: coveralls
xcodeproj: RosettaStoneKit.xcodeproj
workspace: RosettaStoneKit.xcworkspace
scheme: RosettaStoneKit
source_directory: RosettaStoneKit
ignore:
  - Pods/*
  - ../*
