language: objective-c
osx_image: xcode7
script: xcodebuild -workspace RosettaStoneKit.xcworkspace -scheme RosettaStoneKit -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 5" test
