language: objective-c
osx_image: xcode8.3
branches:
  only:
    - master

env:
  - FASTLANE_XCODE_LIST_TIMEOUT=60

before_install:
  - rvm use $RVM_RUBY_VERSION

install:
  - bundle install --without=documentation --path ../travis_bundle_dir
  - bundle exec pod install --repo-update

script: script/ci
