#!/usr/bin/env bash

export OBJROOT="$PWD/build"
export SYMROOT="$PWD/build"

xcodebuild -configuration "Debug" \
           -destination "name=iPhone 5,OS=9.2" \
           -scheme "RosettaStoneKit" \
           -workspace "RosettaStoneKit.xcworkspace" \
           build test | \
  xcpretty --color \
           --report html \
           --output "build/reports/test-report.html" \
           --screenshots \
           --report junit \
           --output "build/reports/test-report.xml"
